In [1]:
import polars as pl

In [2]:
gldv_merged = pl.read_csv(
    "/mnt/yokoyamalab-nas/gldv2-full/csv/v2/merged_set_top_countries_caption_labels.csv"
)
gldv_merged.head()

shape: (5, 14)
┌────────────┬────────────┬───────────┬───────────┬───┬───────┬────────────┬───────────┬───────────┐
│ id         ┆ landmark_i ┆ latitude  ┆ longitude ┆ … ┆ src   ┆ pred_label ┆ pred_scor ┆ caption   │
│ ---        ┆ d          ┆ ---       ┆ ---       ┆   ┆ ---   ┆ ---        ┆ e         ┆ ---       │
│ str        ┆ ---        ┆ f64       ┆ f64       ┆   ┆ str   ┆ str        ┆ ---       ┆ str       │
│            ┆ i64        ┆           ┆           ┆   ┆       ┆            ┆ f64       ┆           │
╞════════════╪════════════╪═══════════╪═══════════╪═══╪═══════╪════════════╪═══════════╪═══════════╡
│ 4b966789e0 ┆ 30319      ┆ 52.226169 ┆ 21.023186 ┆ … ┆ train ┆ palace_cas ┆ 0.9       ┆ Classical │
│ 572456     ┆            ┆           ┆           ┆   ┆       ┆ tle        ┆           ┆ European  │
│            ┆            ┆           ┆           ┆   ┆       ┆            ┆           ┆ building  │
│            ┆            ┆           ┆           ┆   ┆       ┆            ┆           ┆ wi…       │
│ 16d8aa057c ┆ 25719      ┆ 45.58359  ┆ 9.27567   ┆ … ┆ train ┆ non_landma ┆ 0.9       ┆ Informati │
│ dd01b9     ┆            ┆           ┆           ┆   ┆       ┆ rk         ┆           ┆ on board  │
│            ┆            ┆           ┆           ┆   ┆       ┆            ┆           ┆ with text │
│            ┆            ┆           ┆           ┆   ┆       ┆            ┆           ┆ an…       │
│ f1556e1eee ┆ 36639      ┆ 44.0446   ┆ -74.9325  ┆ … ┆ train ┆ non_landma ┆ 0.9       ┆ A small   │
│ ba213f     ┆            ┆           ┆           ┆   ┆       ┆ rk         ┆           ┆ green     │
│            ┆            ┆           ┆           ┆   ┆       ┆            ┆           ┆ plant     │
│            ┆            ┆           ┆           ┆   ┆       ┆            ┆           ┆ growing   │
│            ┆            ┆           ┆           ┆   ┆       ┆            ┆           ┆ on…       │
│ 4072182edd ┆ 2474       ┆ 51.685278 ┆ -2.543611 ┆ … ┆ train ┆ non_landma ┆ 0.9       ┆ A serene  │
│ d0100e     ┆            ┆           ┆           ┆   ┆       ┆ rk         ┆           ┆ stream    │
│            ┆            ┆           ┆           ┆   ┆       ┆            ┆           ┆ flowing   │
│            ┆            ┆           ┆           ┆   ┆       ┆            ┆           ┆ throug…   │
│ 3cdc355c62 ┆ 12877      ┆ 48.862444 ┆ 2.395889  ┆ … ┆ train ┆ non_landma ┆ 0.9       ┆ A         │
│ 32712f     ┆            ┆           ┆           ┆   ┆       ┆ rk         ┆           ┆ memorial  │
│            ┆            ┆           ┆           ┆   ┆       ┆            ┆           ┆ wall with │
│            ┆            ┆           ┆           ┆   ┆       ┆            ┆           ┆ numerous  │
│            ┆            ┆           ┆           ┆   ┆       ┆            ┆           ┆ …         │
└────────────┴────────────┴───────────┴───────────┴───┴───────┴────────────┴───────────┴───────────┘

In [4]:
gldv_merged["pred_label"].unique()

shape: (6,)
Series: 'pred_label' [str]
[
	"palace_castle"
	"monument_statue"
	"arch_gate"
	"non_landmark"
	"tower"
	"bridge"
]

In [ ]:
valid_df = gldv_merged.filter(pl.col("pred_label") != "non_landmark").with_columns(
    (pl.col("country") + "|" + pl.col("pred_label")).alias("stratify_key")
)
valid_df.head()

In [ ]:
from sklearn.model_selection import train_test_split

train_df, test_df = train_test_split(valid_df, test_size=0.2, random_state=42)
train_df, valid_df = train_test_split(train_df, test_size=0.1, random_state=42)

len(train_df), len(valid_df), len(test_df)

In [ ]:
train_df.head()

In [ ]:
train_df = pl.read_csv("/mnt/yokoyamalab-nas/gldv2-full/csv/v2/temp/train.csv")
valid_df = pl.read_csv("/mnt/yokoyamalab-nas/gldv2-full/csv/v2/temp/valid.csv")
test_df = pl.read_csv("/mnt/yokoyamalab-nas/gldv2-full/csv/v2/temp/test.csv")

In [ ]:
train_df.head()