In [1]:
import polars as pl

In [2]:
gldv_merged = pl.read_csv(
    "/mnt/yokoyamalab-nas/gldv2-full/csv/v2/merged_set_top_countries_caption_labels.csv"
)
gldv_merged.head()

shape: (5, 14)
┌────────────┬────────────┬───────────┬───────────┬───┬───────┬────────────┬───────────┬───────────┐
│ id         ┆ landmark_i ┆ latitude  ┆ longitude ┆ … ┆ src   ┆ pred_label ┆ pred_scor ┆ caption   │
│ ---        ┆ d          ┆ ---       ┆ ---       ┆   ┆ ---   ┆ ---        ┆ e         ┆ ---       │
│ str        ┆ ---        ┆ f64       ┆ f64       ┆   ┆ str   ┆ str        ┆ ---       ┆ str       │
│            ┆ i64        ┆           ┆           ┆   ┆       ┆            ┆ f64       ┆           │
╞════════════╪════════════╪═══════════╪═══════════╪═══╪═══════╪════════════╪═══════════╪═══════════╡
│ 4b966789e0 ┆ 30319      ┆ 52.226169 ┆ 21.023186 ┆ … ┆ train ┆ palace_cas ┆ 0.9       ┆ Classical │
│ 572456     ┆            ┆           ┆           ┆   ┆       ┆ tle        ┆           ┆ European  │
│            ┆            ┆           ┆           ┆   ┆       ┆            ┆           ┆ building  │
│            ┆            ┆           ┆           ┆   ┆       ┆            ┆           ┆ wi…       │
│ 16d8aa057c ┆ 25719      ┆ 45.58359  ┆ 9.27567   ┆ … ┆ train ┆ non_landma ┆ 0.9       ┆ Informati │
│ dd01b9     ┆            ┆           ┆           ┆   ┆       ┆ rk         ┆           ┆ on board  │
│            ┆            ┆           ┆           ┆   ┆       ┆            ┆           ┆ with text │
│            ┆            ┆           ┆           ┆   ┆       ┆            ┆           ┆ an…       │
│ f1556e1eee ┆ 36639      ┆ 44.0446   ┆ -74.9325  ┆ … ┆ train ┆ non_landma ┆ 0.9       ┆ A small   │
│ ba213f     ┆            ┆           ┆           ┆   ┆       ┆ rk         ┆           ┆ green     │
│            ┆            ┆           ┆           ┆   ┆       ┆            ┆           ┆ plant     │
│            ┆            ┆           ┆           ┆   ┆       ┆            ┆           ┆ growing   │
│            ┆            ┆           ┆           ┆   ┆       ┆            ┆           ┆ on…       │
│ 4072182edd ┆ 2474       ┆ 51.685278 ┆ -2.543611 ┆ … ┆ train ┆ non_landma ┆ 0.9       ┆ A serene  │
│ d0100e     ┆            ┆           ┆           ┆   ┆       ┆ rk         ┆           ┆ stream    │
│            ┆            ┆           ┆           ┆   ┆       ┆            ┆           ┆ flowing   │
│            ┆            ┆           ┆           ┆   ┆       ┆            ┆           ┆ throug…   │
│ 3cdc355c62 ┆ 12877      ┆ 48.862444 ┆ 2.395889  ┆ … ┆ train ┆ non_landma ┆ 0.9       ┆ A         │
│ 32712f     ┆            ┆           ┆           ┆   ┆       ┆ rk         ┆           ┆ memorial  │
│            ┆            ┆           ┆           ┆   ┆       ┆            ┆           ┆ wall with │
│            ┆            ┆           ┆           ┆   ┆       ┆            ┆           ┆ numerous  │
│            ┆            ┆           ┆           ┆   ┆       ┆            ┆           ┆ …         │
└────────────┴────────────┴───────────┴───────────┴───┴───────┴────────────┴───────────┴───────────┘

In [4]:
valid_df = gldv_merged.filter(pl.col("pred_label") != "non_landmark").with_columns(
    (pl.col("country") + "|" + pl.col("pred_label")).alias("stratify_key")
)
valid_df

shape: (835_161, 15)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ id        ┆ landmark_ ┆ latitude  ┆ longitude ┆ … ┆ pred_labe ┆ pred_scor ┆ caption   ┆ stratify │
│ ---       ┆ id        ┆ ---       ┆ ---       ┆   ┆ l         ┆ e         ┆ ---       ┆ _key     │
│ str       ┆ ---       ┆ f64       ┆ f64       ┆   ┆ ---       ┆ ---       ┆ str       ┆ ---      │
│           ┆ i64       ┆           ┆           ┆   ┆ str       ┆ f64       ┆           ┆ str      │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ 4b966789e ┆ 30319     ┆ 52.226169 ┆ 21.023186 ┆ … ┆ palace_ca ┆ 0.9       ┆ Classical ┆ Poland|p │
│ 0572456   ┆           ┆           ┆           ┆   ┆ stle      ┆           ┆ European  ┆ alace_ca │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ building  ┆ stle     │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ wi…       ┆          │
│ 202cd7955 ┆ 104169    ┆ 56.123889 ┆ -3.947778 ┆ … ┆ palace_ca ┆ 0.9       ┆ Ancient   ┆ United   │
│ 6f30760   ┆           ┆           ┆           ┆   ┆ stle      ┆           ┆ stone     ┆ Kingdom| │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ castle on ┆ palace_c │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ a hill…   ┆ astle    │
│ e9028e1ef ┆ 19756     ┆ 43.275738 ┆ 11.990018 ┆ … ┆ arch_gate ┆ 0.9       ┆ A stone   ┆ Italy|ar │
│ 00e6cff   ┆           ┆           ┆           ┆   ┆           ┆           ┆ arch gate ┆ ch_gate  │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ with dark ┆          │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ wo…       ┆          │
│ 6e901d6b9 ┆ 101718    ┆ 43.881986 ┆ 11.097297 ┆ … ┆ tower     ┆ 0.9       ┆ A tall,   ┆ Italy|to │
│ d4da278   ┆           ┆           ┆           ┆   ┆           ┆           ┆ striped   ┆ wer      │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ tower     ┆          │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ with a l… ┆          │
│ cc6b89c09 ┆ 147865    ┆ 31.21899  ┆ 121.46416 ┆ … ┆ arch_gate ┆ 0.9       ┆ Black     ┆ China|ar │
│ b881029   ┆           ┆           ┆ 3         ┆   ┆           ┆           ┆ metal     ┆ ch_gate  │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ gate with ┆          │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ a plaque… ┆          │
│ …         ┆ …         ┆ …         ┆ …         ┆ … ┆ …         ┆ …         ┆ …         ┆ …        │
│ 514bdb4e3 ┆ 73880     ┆ 48.021944 ┆ 11.861944 ┆ … ┆ tower     ┆ 0.9       ┆ Gothic    ┆ Germany| │
│ aaf5fc0   ┆           ┆           ┆           ┆   ┆           ┆           ┆ cathedral ┆ tower    │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ tower     ┆          │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ with in…  ┆          │
│ 4f444b0bb ┆ 31992     ┆ 32.921    ┆ -117.253  ┆ … ┆ arch_gate ┆ 0.9       ┆ Stone     ┆ United   │
│ a8cdcc0   ┆           ┆           ┆           ┆   ┆           ┆           ┆ building  ┆ States|a │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ with a    ┆ rch_gate │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ sign rea… ┆          │
│ be3420d69 ┆ 49644     ┆ 45.466669 ┆ 9.197553  ┆ … ┆ palace_ca ┆ 0.9       ┆ A grand   ┆ Italy|pa │
│ 5838ba3   ┆           ┆           ┆           ┆   ┆ stle      ┆           ┆ neoclassi ┆ lace_cas │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ cal       ┆ tle      │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ building  ┆          │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ …         ┆          │
│ f07d97acb ┆ 51420     ┆ 52.377329 ┆ 4.59569   ┆ … ┆ arch_gate ┆ 0.9       ┆ A         ┆ Netherla │
│ c9cac79   ┆           ┆           ┆           ┆   ┆           ┆           ┆ historic  ┆ nds|arch │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ brick     ┆ _gate    │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ building  ┆          │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ with…     ┆          │
│ 03947beda ┆ 16254     ┆ 30.327778 ┆ -81.655   ┆ … ┆ arch_gate ┆ 0.9       ┆ Beaux-Art ┆ United   │
│ 4345d37   ┆           ┆           ┆           ┆   ┆           ┆           ┆ s style   ┆ States|a │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ building  ┆ rch_gate │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ with…     ┆          │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

In [5]:
from sklearn.model_selection import train_test_split

train_df, test_df = train_test_split(valid_df, test_size=0.2, random_state=42)
train_df, valid_df = train_test_split(train_df, test_size=0.1, random_state=42)

len(train_df), len(valid_df), len(test_df)

(601315, 66813, 167033)

In [8]:
train_df.head()

shape: (5, 15)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ id        ┆ landmark_ ┆ latitude  ┆ longitude ┆ … ┆ pred_labe ┆ pred_scor ┆ caption   ┆ stratify │
│ ---       ┆ id        ┆ ---       ┆ ---       ┆   ┆ l         ┆ e         ┆ ---       ┆ _key     │
│ str       ┆ ---       ┆ f64       ┆ f64       ┆   ┆ ---       ┆ ---       ┆ str       ┆ ---      │
│           ┆ i64       ┆           ┆           ┆   ┆ str       ┆ f64       ┆           ┆ str      │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ 5224830a1 ┆ 67085     ┆ 34.1211   ┆ 133.001   ┆ … ┆ bridge    ┆ 0.9       ┆ A large   ┆ Japan|br │
│ 9a3f31c   ┆           ┆           ┆           ┆   ┆           ┆           ┆ suspensio ┆ idge     │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ n bridge  ┆          │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ with…     ┆          │
│ b2d54da00 ┆ 152227    ┆ 53.006    ┆ 7.192     ┆ … ┆ bridge    ┆ 0.9       ┆ A red     ┆ Netherla │
│ a70bf24   ┆           ┆           ┆           ┆   ┆           ┆           ┆ wooden    ┆ nds|brid │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ bridge    ┆ ge       │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ over a    ┆          │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ pon…      ┆          │
│ 843af7cc5 ┆ 64521     ┆ 48.431806 ┆ 0.090278  ┆ … ┆ arch_gate ┆ 0.9       ┆ Classical ┆ France|a │
│ cf86f15   ┆           ┆           ┆           ┆   ┆           ┆           ┆ French    ┆ rch_gate │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ architect ┆          │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ ure …     ┆          │
│ 5c7b74468 ┆ 58384     ┆ 46.002    ┆ 12.2867   ┆ … ┆ palace_ca ┆ 0.9       ┆ A         ┆ Italy|pa │
│ 3854d46   ┆           ┆           ┆           ┆   ┆ stle      ┆           ┆ medieval  ┆ lace_cas │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ castle on ┆ tle      │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ a         ┆          │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ hilltop…  ┆          │
│ a2510e80d ┆ 11054     ┆ 40.42189  ┆ -3.682189 ┆ … ┆ monument_ ┆ 0.9       ┆ A dynamic ┆ Spain|mo │
│ 6442d4f   ┆           ┆           ┆           ┆   ┆ statue    ┆           ┆ statue of ┆ nument_s │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ a winged  ┆ tatue    │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ f…        ┆          │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

In [9]:
train_df.write_csv("/mnt/yokoyamalab-nas/gldv2-full/csv/v2/train.csv")
valid_df.write_csv("/mnt/yokoyamalab-nas/gldv2-full/csv/v2/valid.csv")
test_df.write_csv("/mnt/yokoyamalab-nas/gldv2-full/csv/v2/test.csv")