In [1]:
from transformers import AutoModel, AutoTokenizer, AutoProcessor
from PIL import Image
import os
import polars as pl
import torch
from torch.utils.data import DataLoader
import sys
sys.path.append("..")
from src.datasets.mp16 import MP16Dataset
import  torch.nn.functional as F
from tqdm import tqdm

device = "cuda" if torch.cuda.is_available() else "cpu"
clip_model_name = "openai/clip-vit-large-patch14"
base_img_path = "../../datasets/google-landmark/index-img"

prompt_template = "a photo of landmark {label}"

In [2]:
clip_processor = AutoProcessor.from_pretrained(clip_model_name)
clip_tokenizer = AutoTokenizer.from_pretrained(clip_model_name)
clip_model = AutoModel.from_pretrained(clip_model_name).to(device)

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.
The image processor of type `CLIPImageProcessor` is now loaded as a fast processor by default, even if the model checkpoint was saved with a slow processor. This is a breaking change and may produce slightly different outputs. To continue using the slow processor, instantiate this class with `use_fast=False`.

Loading weights:   0%|          | 0/590 [00:00<?, ?it/s]

CLIPModel LOAD REPORT from: openai/clip-vit-large-patch14
Key                                  | Status     |  |
-------------------------------------+------------+--+-
vision_model.embeddings.position_ids | UNEXPECTED |  |
text_model.embeddings.position_ids   | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

In [2]:
df = pl.read_csv("../../datasets/google-landmark/train_ref.csv")
dataset = MP16Dataset(df, img_col="id", img_base_path=base_img_path)

In [4]:
with open("./labels.txt", "r") as f:
    labels = [lb.strip("\n") for lb in f.readlines()]
    labels_prompt = [prompt_template.format(label=lb) for lb in labels]

# add fallback
labels.append("other")
labels_prompt.append("a photo of an indoor scene, a mundane household object, or a generic texture that is not an exterior landmark.")

In [5]:
labels_prompt

['a photo of landmark tower',
 'a photo of landmark lighthouse',
 'a photo of landmark skyscraper',
 'a photo of landmark bridge',
 'a photo of landmark triumphal_arch',
 'a photo of landmark column_arch',
 'a photo of landmark gate',
 'a photo of landmark castle',
 'a photo of landmark fortress',
 'a photo of landmark ruins',
 'a photo of landmark statue',
 'a photo of landmark pillar_monument',
 'a photo of landmark fountain',
 'a photo of landmark park',
 'a photo of landmark mountain_peak',
 'a photo of landmark waterfall',
 'a photo of landmark rock_formation',
 'a photo of landmark aerial_view',
 'a photo of landmark street_scene',
 'a photo of an indoor scene, a mundane household object, or a generic texture that is not an exterior landmark.']

In [6]:
with torch.no_grad():
    label_tokenized = clip_tokenizer(labels_prompt, return_tensors="pt", padding=True)
    label_embedding = clip_model.get_text_features(**{k:v.to(device) for k, v in label_tokenized.items()})
    label_embedding = F.normalize(label_embedding.pooler_output.cpu())

In [7]:
def collate_fn(batch):
    images = [b["image"] for b in batch]
    img_processed = clip_processor(images=images, return_tensors="pt")
    return img_processed
loader = DataLoader(dataset, batch_size=1024, collate_fn=collate_fn)

In [8]:
label_preds = []

with torch.no_grad():
    for batch in tqdm(loader, desc="zero-shot classify"):
        img_embedding = clip_model.get_image_features(**{k:v.to(device) for k, v in batch.items()})
        img_embedding = F.normalize(img_embedding.pooler_output.cpu())
        
        similarities = img_embedding @ label_embedding.T
        predicted = torch.argmax(similarities.softmax(dim=-1), dim=-1).tolist()
        label_preds.extend(predicted)

        torch.cuda.empty_cache()
        del img_embedding
        del similarities

zero-shot classify: 100%|██████████| 1781/1781 [6:10:32<00:00, 12.48s/it]

In [12]:
df_pred = df.with_columns(pl.Series("pred_label", [labels[lp] for lp in label_preds]))

In [20]:
df_pred.filter(pl.col("pred_label") != "other")

shape: (1_623_375, 20)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ landmark_ ┆ input_url ┆ resolved_ ┆ geohack_u ┆ … ┆ subregion ┆ id        ┆ url       ┆ pred_lab │
│ id        ┆ ---       ┆ url       ┆ rl        ┆   ┆ ---       ┆ ---       ┆ ---       ┆ el       │
│ ---       ┆ str       ┆ ---       ┆ ---       ┆   ┆ str       ┆ str       ┆ str       ┆ ---      │
│ i64       ┆           ┆ str       ┆ str       ┆   ┆           ┆           ┆           ┆ str      │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ 104169    ┆ http://co ┆ https://c ┆ https://g ┆ … ┆ Northern  ┆ 202cd7955 ┆ http://up ┆ castle   │
│           ┆ mmons.wik ┆ ommons.wi ┆ eohack.to ┆   ┆ Europe    ┆ 6f30760   ┆ load.wiki ┆          │
│           ┆ imedia.or ┆ kimedia.o ┆ olforge.o ┆   ┆           ┆           ┆ media.org ┆          │
│           ┆ g/w…      ┆ rg/…      ┆ rg/…      ┆   ┆           ┆           ┆ /wi…      ┆          │
│ 2474      ┆ http://co ┆ https://c ┆ https://g ┆ … ┆ Northern  ┆ 4072182ed ┆ https://u ┆ waterfal │
│           ┆ mmons.wik ┆ ommons.wi ┆ eohack.to ┆   ┆ Europe    ┆ dd0100e   ┆ pload.wik ┆ l        │
│           ┆ imedia.or ┆ kimedia.o ┆ olforge.o ┆   ┆           ┆           ┆ imedia.or ┆          │
│           ┆ g/w…      ┆ rg/…      ┆ rg/…      ┆   ┆           ┆           ┆ g/w…      ┆          │
│ 6888      ┆ http://co ┆ https://c ┆ https://g ┆ … ┆ Eastern   ┆ 6f31b874d ┆ https://u ┆ park     │
│           ┆ mmons.wik ┆ ommons.wi ┆ eohack.to ┆   ┆ Europe    ┆ 1a4d489   ┆ pload.wik ┆          │
│           ┆ imedia.or ┆ kimedia.o ┆ olforge.o ┆   ┆           ┆           ┆ imedia.or ┆          │
│           ┆ g/w…      ┆ rg/…      ┆ rg/…      ┆   ┆           ┆           ┆ g/w…      ┆          │
│ 25719     ┆ http://co ┆ https://c ┆ https://g ┆ … ┆ Southern  ┆ 16d8aa057 ┆ http://up ┆ column_a │
│           ┆ mmons.wik ┆ ommons.wi ┆ eohack.to ┆   ┆ Europe    ┆ cdd01b9   ┆ load.wiki ┆ rch      │
│           ┆ imedia.or ┆ kimedia.o ┆ olforge.o ┆   ┆           ┆           ┆ media.org ┆          │
│           ┆ g/w…      ┆ rg/…      ┆ rg/…      ┆   ┆           ┆           ┆ /wi…      ┆          │
│ 122849    ┆ http://co ┆ https://c ┆ https://g ┆ … ┆ Western   ┆ 3968e37e5 ┆ https://u ┆ castle   │
│           ┆ mmons.wik ┆ ommons.wi ┆ eohack.to ┆   ┆ Europe    ┆ 03f3109   ┆ pload.wik ┆          │
│           ┆ imedia.or ┆ kimedia.o ┆ olforge.o ┆   ┆           ┆           ┆ imedia.or ┆          │
│           ┆ g/w…      ┆ rg/…      ┆ rg/…      ┆   ┆           ┆           ┆ g/w…      ┆          │
│ …         ┆ …         ┆ …         ┆ …         ┆ … ┆ …         ┆ …         ┆ …         ┆ …        │
│ 46054     ┆ http://co ┆ https://c ┆ https://g ┆ … ┆ South     ┆ b4e2a7c6c ┆ https://u ┆ mountain │
│           ┆ mmons.wik ┆ ommons.wi ┆ eohack.to ┆   ┆ America   ┆ 2a2c899   ┆ pload.wik ┆ _peak    │
│           ┆ imedia.or ┆ kimedia.o ┆ olforge.o ┆   ┆           ┆           ┆ imedia.or ┆          │
│           ┆ g/w…      ┆ rg/…      ┆ rg/…      ┆   ┆           ┆           ┆ g/w…      ┆          │
│ 49555     ┆ http://co ┆ https://c ┆ https://g ┆ … ┆ Northern  ┆ 9b0e881f2 ┆ https://u ┆ street_s │
│           ┆ mmons.wik ┆ ommons.wi ┆ eohack.to ┆   ┆ Europe    ┆ ead47d1   ┆ pload.wik ┆ cene     │
│           ┆ imedia.or ┆ kimedia.o ┆ olforge.o ┆   ┆           ┆           ┆ imedia.or ┆          │
│           ┆ g/w…      ┆ rg/…      ┆ rg/…      ┆   ┆           ┆           ┆ g/w…      ┆          │
│ 42142     ┆ http://co ┆ https://c ┆ https://g ┆ … ┆ Southern  ┆ 8877b1c33 ┆ https://u ┆ statue   │
│           ┆ mmons.wik ┆ ommons.wi ┆ eohack.to ┆   ┆ Europe    ┆ 3e1f1ad   ┆ pload.wik ┆          │
│           ┆ imedia.or ┆ kimedia.o ┆ olforge.o ┆   ┆           ┆           ┆ imedia.or ┆          │
│           ┆ g/w…      ┆ rg/…      ┆ rg/…      ┆   ┆           ┆           ┆ g/w…      ┆          │
│ 83144     ┆ http://co ┆ https://c ┆ https://g ┆ … ┆ Eastern   ┆ e61947261 ┆ https://u ┆ gate     │
│           ┆ mmons.wik ┆ ommons.wi ┆ eohack.to ┆   ┆ Europe    ┆ 3f58db4   ┆ pload.wik ┆          │
│           ┆ imedia.or ┆ kimedia.o ┆ olforge.o ┆   ┆           ┆           ┆ imedia.or ┆          │
│           ┆ g/w…      ┆ rg/…      ┆ rg/…      ┆   ┆           ┆           ┆ g/w…      ┆          │
│ 34698     ┆ http://co ┆ https://c ┆ https://g ┆ … ┆ Northern  ┆ 8ef8dff6f ┆ https://u ┆ castle   │
│           ┆ mmons.wik ┆ ommons.wi ┆ eohack.to ┆   ┆ Europe    ┆ c4790c2   ┆ pload.wik ┆          │
│           ┆ imedia.or ┆ kimedia.o ┆ olforge.o ┆   ┆           ┆           ┆ imedia.or ┆          │
│           ┆ g/w…      ┆ rg/…      ┆ rg/…      ┆   ┆           ┆           ┆ g/w…      ┆          │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

In [24]:
df_pred.write_csv("../../datasets/google-landmark/train_ref_predicted.csv")

In [31]:
df_index = pl.read_csv("../../datasets/google-landmark/index_ref.csv")
dataset_index = MP16Dataset(df_index, img_col="id", img_base_path=base_img_path)
loader_index = DataLoader(dataset_index, batch_size=1024, collate_fn=collate_fn)

In [32]:
index_label_preds = []

with torch.no_grad():
    for batch in tqdm(loader_index, desc="zero-shot classify"):
        img_embedding = clip_model.get_image_features(**{k:v.to(device) for k, v in batch.items()})
        img_embedding = F.normalize(img_embedding.pooler_output.cpu())
        
        similarities = img_embedding @ label_embedding.T
        predicted = torch.argmax(similarities.softmax(dim=-1), dim=-1).tolist()
        index_label_preds.extend(predicted)

        torch.cuda.empty_cache()
        del img_embedding
        del similarities

zero-shot classify: 100%|██████████| 404/404 [1:22:14<00:00, 12.21s/it]

In [34]:
df_index_pred = df_index.with_columns(pl.Series("pred_label", [labels[lp] for lp in index_label_preds]))
df_index_pred.head()

shape: (5, 19)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ landmark_ ┆ input_url ┆ resolved_ ┆ geohack_u ┆ … ┆ continent ┆ subregion ┆ id        ┆ pred_lab │
│ id        ┆ ---       ┆ url       ┆ rl        ┆   ┆ ---       ┆ ---       ┆ ---       ┆ el       │
│ ---       ┆ str       ┆ ---       ┆ ---       ┆   ┆ str       ┆ str       ┆ str       ┆ ---      │
│ i64       ┆           ┆ str       ┆ str       ┆   ┆           ┆           ┆           ┆ str      │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ 78775     ┆ http://co ┆ https://c ┆ https://g ┆ … ┆ Americas  ┆ Northern  ┆ 6c07a95bb ┆ fortress │
│           ┆ mmons.wik ┆ ommons.wi ┆ eohack.to ┆   ┆           ┆ America   ┆ ed8387a   ┆          │
│           ┆ imedia.or ┆ kimedia.o ┆ olforge.o ┆   ┆           ┆           ┆           ┆          │
│           ┆ g/w…      ┆ rg/…      ┆ rg/…      ┆   ┆           ┆           ┆           ┆          │
│ 14854     ┆ http://co ┆ https://c ┆ https://g ┆ … ┆ Americas  ┆ Northern  ┆ fa69da76c ┆ mountain │
│           ┆ mmons.wik ┆ ommons.wi ┆ eohack.to ┆   ┆           ┆ America   ┆ 3eb58ea   ┆ _peak    │
│           ┆ imedia.or ┆ kimedia.o ┆ olforge.o ┆   ┆           ┆           ┆           ┆          │
│           ┆ g/w…      ┆ rg/…      ┆ rg/…      ┆   ┆           ┆           ┆           ┆          │
│ 38501     ┆ http://co ┆ https://c ┆ https://g ┆ … ┆ Europe    ┆ Northern  ┆ 34f7a1701 ┆ street_s │
│           ┆ mmons.wik ┆ ommons.wi ┆ eohack.to ┆   ┆           ┆ Europe    ┆ 86c9a60   ┆ cene     │
│           ┆ imedia.or ┆ kimedia.o ┆ olforge.o ┆   ┆           ┆           ┆           ┆          │
│           ┆ g/w…      ┆ rg/…      ┆ rg/…      ┆   ┆           ┆           ┆           ┆          │
│ 36227     ┆ http://co ┆ https://c ┆ https://g ┆ … ┆ Americas  ┆ Northern  ┆ 2eaf1281b ┆ column_a │
│           ┆ mmons.wik ┆ ommons.wi ┆ eohack.to ┆   ┆           ┆ America   ┆ 9715e91   ┆ rch      │
│           ┆ imedia.or ┆ kimedia.o ┆ olforge.o ┆   ┆           ┆           ┆           ┆          │
│           ┆ g/w…      ┆ rg/…      ┆ rg/…      ┆   ┆           ┆           ┆           ┆          │
│ 39704     ┆ http://co ┆ https://c ┆ https://g ┆ … ┆ Asia      ┆ Southeast ┆ d3b133281 ┆ gate     │
│           ┆ mmons.wik ┆ ommons.wi ┆ eohack.to ┆   ┆           ┆ Asia      ┆ 4fc7b80   ┆          │
│           ┆ imedia.or ┆ kimedia.o ┆ olforge.o ┆   ┆           ┆           ┆           ┆          │
│           ┆ g/w…      ┆ rg/…      ┆ rg/…      ┆   ┆           ┆           ┆           ┆          │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

In [36]:
df_index_pred.write_csv("../../datasets/google-landmark/index_ref_predicted.csv")

In [46]:
df_pred.filter(pl.col("pred_label").is_in(labels[:12])).write_csv("../../datasets/google-landmark/train_ref_predicted_filtered.csv")
df_index_pred.filter(pl.col("pred_label").is_in(labels[:12])).write_csv("../../datasets/google-landmark/index_ref_predicted_filtered.csv")